### PR TITLE
[PLAYER-2376] Update cast sdk v2->v3

### PR DESCRIPTION
**Pull request by M0rtyMerr**

### CODE REVIEW

**Review by IvanSakharovskii — APPROVED** [review]

**Comment by brol1dev** [comment]
We've merged the code in the core sdk and we have it available in candidate now. I see there are conflicts with this PR now if we try to merge it to candidate. Can you fix them?

**Comment by M0rtyMerr** [comment]
@rcvrgs done

**Review by brol1dev — CHANGES_REQUESTED** [review]
Running the sample app doesn't work. There are linking errors because it cannot find some classes. Please fix.

I even tested merging this branch into `candidate` to see if that fixes the issue but it doesn't. I think you might have created the core SDK from your side and included it in this PR.

Let us know how we can help.

**Comment by MortMerr** [comment]
@rcvrgs Sorry, it was my fault, forget to clean project before verifying successful building. Fix method names.

**Comment by M0rtyMerr** [comment]
@rcvrgs now it should be ok.

**Review by brol1dev — CHANGES_REQUESTED** [review]
@IvanSakharovskii, @MortMerr, we made a new RC today and it is conflicting on the vendor SDK. You need to remove the modified SDK in this PR since we don't want it to change the one in candidate.

**Comment by MortMerr** [comment]
@rcvrgs then we don't need this pr. We can't update cast-sample-app without updating cast sdk.

**Comment by akshaydch11** [comment]
LGTM

**Pull request merged**
