### PR TITLE
[Player-5279] Player Controls size reduced and not appropriate

### PR DESCRIPTION
**Pull request by oSulyma**
Added constraints

### CODE REVIEW

**Comment by oSulyma** [comment]
@Artur-Sakhno 
Size are fixed for iPhone-X , but there is a white stripe (under the bottom bar with controls) for iPhone-7 both in iOS > 11 and lower then 11. See attachments. Please, fix it.
white stripe

**Comment by oSulyma** [comment]
Need work

**Review by oSulyma — COMMENTED** [review]
LGFM.
@DmitriiMaslov  I can't make approve action,  because I created this PR instead of Artur. So, please, approve it instead of me.

**Review by DmitriiMaslov — CHANGES_REQUESTED** [review]
Please point to Dev instead of Candidate. This issue was waved for the current release and we don't to merge anything to Candidate now. Thank you.

**Review by maxkupetskii — APPROVED** [review]

**Review by DmitriiMaslov — APPROVED** [review]

**Pull request merged**
